# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lbarreta <lbarreta@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/12/08 21:51:19 by jaqrodri          #+#    #+#              #
#    Updated: 2019/12/08 22:14:02 by lbarreta         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-02
FT_1 = function1_rush02.c
FT_2 = function2_rush02.c
FT_3 = function3_rush02.c
MAIN = rush_02.c

all:
	cc -Wall -Wextra -Werror -o rush-02 $(MAIN) $(FT_1) $(FT_2) $(FT_3)
clean:
	/bin/rm -f *.o
fclean: clean
	/bin/rm -f $(NAME)